import { type Config, type Options, defineConfig } from "orval"

const OPENAPI_GATEWAY_ORIGIN =
  process.env.OPENAPI_GATEWAY_ORIGIN ?? "http://localhost:8080"

const GENERATED_ROOT = "src/shared/api/generated"

const GENERATED_HEADER = (info?: { title?: string }) => [
  "@ts-nocheck",
  "/* eslint-disable */",
  "Generated by Orval",
  "Do not edit manually.",
  ...(info?.title ? [info.title] : []),
]

const createProject = ({
  name,
  inputPath,
  runtimeBasePath,
}: {
  name: string
  inputPath: string
  runtimeBasePath: string
}): Options => {
  return {
    input: {
      target: new URL(inputPath, OPENAPI_GATEWAY_ORIGIN).toString(),
    },
    output: {
      mode: "tags-split",
      target: `${GENERATED_ROOT}/${name}/endpoints`,
      schemas: {
        path: `${GENERATED_ROOT}/${name}/schemas`,
        type: "zod",
      },
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      namingConvention: "kebab-case",
      baseUrl: {
        runtime: `(process.env.NEXT_PUBLIC_APP_ORIGIN ?? "") + "${runtimeBasePath}"`,
      },
      override: {
        header: GENERATED_HEADER,
        query: {
          useSuspenseQuery: true,
          usePrefetch: true,
          useInvalidate: true,
          useSetQueryData: true,
          useGetQueryData: true,
          signal: true,
        },
        fetch: {
          includeHttpResponseReturnType: false,
          forceSuccessResponse: true,
          runtimeValidation: true,
        },
      },
    },
  }
}

export default defineConfig((): Config => {
  return {
    "profile-api": createProject({
      name: "profile",
      inputPath: "/api/profile/v3/api-docs",
      runtimeBasePath: "/api/proxy/profile",
    }),

    "echo-api": createProject({
      name: "echo",
      inputPath: "/api/echo/v3/api-docs",
      runtimeBasePath: "/api/proxy/echo",
    }),
  }
})
